game/urls.py
from django.urls import path
from game.views import *

app_name="game"

urlpatterns = [

    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('single/', single, name='single'),
    path('games/', games, name='games'),
    path('review/', review, name='review'),
    path('blog/', blog, name='blog'),
    path('about/', about, name='about'),
    path('search/', search, name='Search'),


]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from django.urls import path, include
# from game import views as v

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('game.urls')),


    path('accounts/', include('allauth.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
from django.contrib.auth.models import User



from django.db import models
from django.conf import settings
from django.db import models


class SearchQuery(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    query = models.CharField(max_length=220)
    timestamp = models.DateTimeField(auto_now_add=True)

game/views.py
from django.shortcuts import render, redirect, render_to_response
from django.shortcuts import render



from .models import SearchQuery


from .models import User

def home(request):

    return render(request, "index.html")



def contact(request):
    return render(request, "contact.html")



def about(request):
    return render(request, "about.html")

def single(request):
    return render(request, "single.html")



def games(request):
    return render(request, "games.html")



def review(request):
    return render(request, "review.html")


def blog(request):
    return render(request, "blog.html")





def search(request):
    query = request.GET.get('q', None)
    user = None
    if request.user.is_authenticated:
        user = request.user
    context =  {"query": query}
    if query is not None:
        SearchQuery.objects.create(user=user, query=query)
        blog_list = BlogPost.objects.search(query=query)
        context['blog_list'] = blog_list
    return render(request, 'search.html')

templates/blog.html
{% extends 'index.html' %}
{% block content %}
{% load staticfiles %}
<html lang="zxx">
<head>
	<title>EndGam - Gaming Magazine Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="/static/img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>


	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>



	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="https://in.pinterest.com/"><i class="fa fa-pinterest"></i></a>
				<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/login?lang=en"><i class="fa fa-twitter"></i></a>
				<a href="https://dribbble.com/"><i class="fa fa-dribbble"></i></a>
				<a href="https://www.behance.net/"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="index.html" class="site-logo">
					<img src="/static/img/logo.png" alt="">
				</a>

				<nav class="top-nav-area w-100">
						<div class="user-panel">
<!--						<a href="">Login</a> / <a href="">Register</a>-->

              <ul class="main-menu primary-menu">
						{% if user.is_authenticated %}
                           <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
                           <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
						{% else %}

                            <li><a href="{% url 'account_login' %}">Sign In</a></li>
                            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
						{% endif %}
			  </ul>

					</div>
				<ul class="main-menu primary-menu">

                        <li><a href="{% url 'game:home' %}">Home</a>
						<li><a href="{% url 'game:games' %}">Games</a>
						<li><a href="{% url 'game:single' %}">Game Singel</a></li>

						<li><a href="{% url 'game:review' %}">Reviews</a></li>
						<li><a href="{% url 'game:contact' %}">Contact</a></li>
						<li><a href="{% url 'game:blog' %}">Blog</a></li>
							</ul>
						</li>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header section end -->


	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="/static/img/page-top-bg/3.jpg">
		<div class="page-info">
			<h2>Blog</h2>
			<div class="site-breadcrumb">
				<a href="">Home</a>  /
				<span>Blog</span>
			</div>
		</div>
	</section>
	<!-- Page top end-->


	<!-- Blog page -->
	<section class="blog-page">
		<div class="container">
			<div class="row">
				<div class="col-xl-9 col-lg-8 col-md-7">
					<ul class="blog-filter">
						<li><a href="https://poki.com/en/racing">Racing</a></li>
						<li><a href="https://poki.com/en/shooting">Shooters</a></li>
						<li><a href="https://www.gamesgames.com/games/strategy">Strategy</a></li>

					</ul>
					<div class="big-blog-item">
						<img src="/static/img/blog-big/1.jpg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta"><a href="">Games</a></div>
							<h3>The best VR games on the market</h3>
							<p>Virtual reality (VR) has been on the cusp of "going mainstream" for a few years now.

								But whether it's been down to marketing, a lack of great games on offer or really expensive headsets, it just didn't take off. Well, until now. Between the Oculus Rift, HTC Vive, PlayStation VR and now the cheaper Oculus Go, the buzz around VR continues to grow. This time it doesn't look like it's set to die out, especially with Oculus launching the standalone, high-performing Oculus Quest.

							....</p>
							<a href="https://www.techradar.com/best/the-best-vr-games" class="read-more">Read More <img src="/static/img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="/static/img/cs.jpeg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta"> <a href="http://www.gamessumo.com/action-games/counter-strike-online-2">Counter-Strike</a></div>
							<h3>The best online game is out now!</h3>
							<p>Counter-Strike (CS) is a series of multiplayer first-person shooter video games, in which teams of terrorists battle to perpetrate an act of terror (bombing, hostage-taking, assassination) and counter-terrorists try to prevent it (bomb defusal, hostage rescue). ....
							</p>
							<a href="https://en.wikipedia.org/wiki/Counter-Strike" class="read-more">Read More <img src="/static/img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="/static/img/PUBG.jpg" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta"> <a href="http://www.gamessumo.com/action-games/pubg-online">PUBG</a></div>
							<h3>The best online game is out now!</h3>
							<p>PlayerUnknown's Battlegrounds (PUBG) is an online multiplayer battle royale game developed and published by PUBG Corporation, a subsidiary of South Korean video game company Bluehole. The game is based on previous mods that were created by Brendan "PlayerUnknown" Greene for other games.......
							</p>
							<a href="https://en.wikipedia.org/wiki/PlayerUnknown%27s_Battlegrounds" class="read-more">Read More <img src="/static/img/icons/double-arrow.png" alt="#"/></a>
						</div>
					</div>
					<div class="site-pagination">
						<a href="#" class="active">01.</a>
						<a href="#">02.</a>
						<a href="#">03.</a>
					</div>
				</div>



				<div class="col-xl-3 col-lg-4 col-md-5 sidebar">
					<div id="stickySidebar">
						<div class="widget-item">
							<form class="search-widget">
								<input type="text">
<!--								<button>search</button>-->
								 <button onclick="window.location.href = 'search.html';">Search Here</button>

							</form>
						</div>


						<div class="widget-item">
							<h4 class="widget-title">Trending</h4>
							<div class="trending-widget">
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="/static/img/1.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta"> <a href="https://store.steampowered.com/genre/Free%20to%20Play/">Divinity: Original Sin 2</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="/static/img/2.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta"> <a href="https://store.steampowered.com/app/501300/What_Remains_of_Edith_Finch/">What Remains of Edith Finch</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="/static/img/3.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta"><a href="https://store.ubi.com/ie/search?q=Rainbow%20Six%20Siege">Rainbow Six Siege</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="/static/img/4.jpg" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta"> <a href="https://store.steampowered.com/app/594570/Total_War_WARHAMMER_II/">Total War: Warhammer 2</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<div class="categories-widget">
								<h4 class="widget-title">categories</h4>
								<ul>
									<li><a href="https://www.mmogames.com/gameslist/">Games</a></li>
									<li><a href="http://2048game.com/tips-and-tricks/">Gaming Tips & Tricks</a></li>
									<li><a href="https://www.crazygames.com/t/3d">Online Games</a></li>
									<li><a href="https://www.wrike.com/blog/team-building-games/">Team Games</a></li>
									<li><a href="https://www.communitygames.ie/">Community</a></li>
									<li><a href="https://realgames.co/category/uncategorized/">Uncategorized</a></li>
								</ul>
							</div>
						</div>
						<div class="widget-item">
							<h4 class="widget-title">Latest Comments</h4>
							<div class="latest-comments">
								<div class="lc-item">
									<img src="/static/img/blog-widget/1.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="/static/img/blog-widget/2.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="/static/img/blog-widget/3.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="/static/img/blog-widget/4.jpg" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<a href="#" class="add">
								<img src="/static/img/add.jpg" alt="">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog page end-->

	<!-- Newsletter section -->
	<section class="newsletter-section">
		<div class="container">
			<h2>Subscribe to our newsletter</h2>
			<form class="newsletter-form">
				<input type="text" placeholder="ENTER YOUR E-MAIL">
				<button class="site-btn">subscribe <img src="/static/img/icons/double-arrow.png" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="footer-left-pic">
				<img src="/static/img/footer-left-pic.png" alt="">
			</div>
			<div class="footer-right-pic">
				<img src="/static/img/footer-right-pic.png" alt="">
			</div>
			<a href="#" class="footer-logo">
				<img src="/static/img/logo.png" alt="">
			</a>

           <ul class="main-menu footer-menu">


			</ul>
			<div class="footer-social d-flex justify-content-center">
				<a href="https://in.pinterest.com/"><i class="fa fa-pinterest"></i></a>
				<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
				<a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
				<a href="https://www.dribble.com/"><i class="fa fa-dribbble"></i></a>
				<a href="https://www.behance.com/"><i class="fa fa-behance"></i></a>
			</div>
			<div class="Rohit Jamwal"><a href="">click here and go to top</a>    <p><font size="5" color="red" >This website is created by Rohit Jamwal</font></p>
		</div>
	</footer>

	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>




	</body>
</html>

   {% endblock %}

templates/contact.html
{% extends 'index.html' %}

{% block title %}Contact - {{ block.super }}{% endblock %}

{% block content %}
{% load staticfiles %}
	<title>EndGam - Gaming Magazine Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="/static/img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>


	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>



	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="https://in.pinterest.com/"><i class="fa fa-pinterest"></i></a>
				<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/login?lang=en"><i class="fa fa-twitter"></i></a>
				<a href="https://dribbble.com/"><i class="fa fa-dribbble"></i></a>
				<a href="https://www.behance.net/"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="{% url 'game:home'%}" class="site-logo">
					<img src="/static/img/logo.png" alt="Home">
				</a>
				<nav class="top-nav-area w-100">
					<div class="user-panel">
<!--						<a href="">Login</a> / <a href="">Register</a>-->

              <ul class="main-menu primary-menu">
						{% if user.is_authenticated %}
                           <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
                           <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
						{% else %}

                            <li><a href="{% url 'account_login' %}">Sign In</a></li>
                            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
						{% endif %}
			  </ul>

					</div>
					<!-- Menu -->
					<ul class="main-menu primary-menu">
 						<li><a href="{% url 'game:home' %}">Home</a>
						<li><a href="{% url 'game:games' %}">Games</a>
						<li><a href="{% url 'game:single' %}">Game Singel</a></li>

						<li><a href="{% url 'game:review' %}">Reviews</a></li>
						<li><a href="{% url 'game:contact' %}">Contact</a></li>
						<li><a href="{% url 'game:blog' %}">Blog</a></li>
							</ul>
						</li>

<!--							<ul class="sub-menu">-->


					</ul>
				</nav>
			</div>
		</div>
	</header>


<section class="page-top-section set-bg" data-setbg="/static/img/page-top-bg/4.jpg" >
		<div class="page-info">
			<h2>Contact</h2>
			<div class="site-breadcrumb">
				<a href="{% url 'game:home' 	%}">Home</a>
				<span>Contact</span>
			</div>
		</div>
	</section>




	<section class="contact-page">
		<div class="container">
			<div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d14376.077865872314!2d-73.879277264103!3d40.757667781624285!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1546528920522" style="border:0" allowfullscreen></iframe></div>
			<div class="row">
				<div class="col-lg-7 order-2 order-lg-1">
					<form class="contact-form">
						<input type="text" placeholder="Your name">
						<input type="text" placeholder="Your e-mail">
						<input type="text" placeholder="Subject">
						<textarea placeholder="Message"></textarea>
						<button class="site-btn">Send message<img src="/static/img/icons/double-arrow.png" alt="#"/></button>
					</form>
				</div>
				<div class="col-lg-5 order-1 order-lg-2 contact-text text-white">
					<h3>Howdy! Say hello</h3>
					<p>Hello This is Rohit Jamwal.</p>
					<div class="cont-info">
						<div class="ci-icon"><img src="/static/img/icons/location.png" alt=""></div>
						<div class="ci-text">Balongi, Mohali, Chandigarh</div>
					</div>
					<div class="cont-info">
						<div class="ci-icon"><img src="/static/img/icons/phone.png" alt=""></div>
						<div class="ci-text">+91 7018192644</div>
					</div>
					<div class="cont-info">
						<div class="ci-icon"><img src="/static/img/icons/mail.png" alt=""></div>
						<div class="ci-text">jamwalrohit06@gmail.com</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Contact page end-->


	<section class="newsletter-section">
		<div class="container">
			<h2>Subscribe to our newsletter</h2>
			<form class="newsletter-form">
				<input type="text" placeholder="ENTER YOUR E-MAIL">
				<button class="site-btn">subscribe  <img src="/static/img/icons/double-arrow.png" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">
			<div class="footer-left-pic">
				<img src="/static/img/footer-left-pic.png" alt="">
			</div>
			<div class="footer-right-pic">
				<img src="/static/img/footer-right-pic.png" alt="">
			</div>
			<a href="#" class="footer-logo">
				<img src="/static/img/logo.png" alt=" Gaming Site">
			</a>

			<div class="footer-social d-flex justify-content-center">
				<a href="https://in.pinterest.com/"><i class="fa fa-pinterest"></i></a>
				<a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
				<a href="https://twitter.com/login?lang=en"><i class="fa fa-twitter"></i></a>
				<a href="https://dribbble.com/"><i class="fa fa-dribbble"></i></a>
				<a href="https://www.behance.net/"><i class="fa fa-behance"></i></a>
			</div>
			<div class="Rohit Jamwal"><a href="">click here and go to top</a>    <p><font size="5" color="red" >This website is created by Rohit Jamwal</font></p>
		</div>
	</footer>
	<!-- Footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>
{% endblock  %}

templates/search.html
{% extends 'index.html' %}


{% block content %}
{% load staticfiles %}

<div class='row'>
    <div class='col-12 col-8 mx-auto'>
                {% if query %}

                     <p class='lead'>You searched for {{ query }}</p>
                {% else %}

                    <form class="form-inline my-2 my-lg-0" action='/search/'>
                  <input class="form-control mr-sm-2" type="search" name='q' placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>


                {% endif %}


                {% for blog_item in blog_list %}

                      {% include 'blog/list-inline.html' with blog_post=blog_item truncate=True detail=False %}
                {% endfor %}


    </div>


</div>

{% endblock %}